version: '3.8'

services:
  server-dev:
    container_name: server-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - '5000:5000'
    env_file:
      - .env
