service: watchtree-server

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  app:
    handler: src/serverless.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
